# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# SITE SETTINGS
title: GloBAM
description: >
  Towards monitoring, understanding and forecasting global biomass flows 
  of aerial migrants.
email: globam@vogelwarte.ch
author: GloBAM partners
url: "http://globam.science" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog

# SOCIAL PROFILES
twitter_username: globam_net
github_username: enram

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish
logo: assets/img/nav_logo.png
posts_on_home: 0 # Don't show news on the homepage (yet)
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/news/:slug/"
